### ISSUE TITLE
Is the Merging of bed files with respect to strand?

### ISSUE THREAD

**Issue by songtaogui** [shiquan/bamdst#10]
Hi,
I have some gene annotations in bed format, and I would like to calculate the reads coverage use your wonderful bamdst. But since it mandatorily merged region files first, I would split my bed file into several non overlap files. So I was wondering that does the merging in bamdst consider strand information? 

best wishes

songtao gui

**Comment by shiquan** [comment]
As you already known bamdst will merge all regions at first step, strand information will be lost during this process. I cannot add support for this in a short time; perhaps you may divider the overlapped genes into different bed files and count separately. Is it necessary to consider strand for the target regions?  I doubt that. But if you really need it, I think you might try to use tabix to generate coverage and depth information from depths.tsv.gz
