### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by elainebblythe** [shiquan/bamdst#14]
hi，When I installed bamdst，I get this error:
$ make
rm -fr gmon.out *.o a.out *.exe *.dSYM  bamdst *~ *.a target.dep *.plot *.report *.tsv.gz uncover.bed
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. bgzf.c -o bgzf.o
In file included from bgzf.c:31:0:
bgzf.h:33:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:29: bgzf.o] Error 1

I check  the /usr/include,the zlib.h is exist.How can I solve this problem？

**Comment by shiquan** [comment]
I believe this error caused due to zlib isn't installed on you system properly. Try to install zlib on your system first. Let me know if you have any further questions.

**Comment by shiquan** [comment]
Do you fix this issue? If so I will close this thread.

**Comment by elainebblythe** [comment]
yes,
thanks.



elaineylq@163.com
 
From: shiquan
Date: 2019-03-08 13:30
To: shiquan/bamdst
CC: elainebblythe; Author
Subject: Re: [shiquan/bamdst] make error (#14)
Do you fix this issue? If so I will close this thread.
