### ISSUE TITLE
mapped reads

### ISSUE THREAD

**Issue by N-damo** [shiquan/bamdst#15]
Hi,
why mapped reads count differ greatly from the result of `samtools view -c -F 4 *.bam`. In bamdst, how to get mapped reads?
best regards
Li'anLin

**Comment by shiquan** [comment]
bamdst will filter QC failed reads, supplementary reads, and secondary reads before count the mapped reads. Try to use `samtools view -c -F 2820` to check your BAM file. And please let me know your test results, so I can update this issue.

**Comment by N-damo** [comment]
cool, `samtools view -c -F 2820` correctly solved my problem.Thank you!
