### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Garvin-Hu** [shiquan/bamdst#16]
Hi there, when I tried to install bamdst, I got a lot of warnings:

rm -fr gmon.out *.o a.out *.exe *.dSYM  bamdst *~ *.a target.dep *.plot *.report *.tsv.gz uncover.bed
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. bgzf.c -o bgzf.o
bgzf.c:80:1: warning: unused function 'kh_clear_cache' [-Wunused-function]
KHASH_MAP_INIT_INT64(cache, cache_t)
^
./khash.h:601:2: note: expanded from macro 'KHASH_MAP_INIT_INT64'
        KHASH_INIT(name, khint64_t, khval_t, 1, kh_int64_hash_func, kh_i...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:215:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:93:1: note: expanded from here
kh_clear_cache
^
1 warning generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. kstring.c -o kstring.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. samlib/bam_aux.c -o bam_aux.o
samlib/bam_aux.c:5:1: warning: unused function 'kh_clear_s' [-Wunused-function]
KHASH_MAP_INIT_STR(s, int)
^
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:215:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:88:1: note: expanded from here
kh_clear_s
^
samlib/bam_aux.c:5:1: warning: unused function 'kh_del_s' [-Wunused-function]
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:341:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:102:1: note: expanded from here
kh_del_s
^
samlib/bam_aux.c:6:1: warning: unused function 'kh_init_r2l' [-Wunused-function]
KHASH_MAP_INIT_STR(r2l, str_p)
^
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:204:23: note: expanded from macro '__KHASH_IMPL'
        SCOPE kh_##name##_t *kh_init_##name(void) ...
                             ^
<scratch space>:109:1: note: expanded from here
kh_init_r2l
^
samlib/bam_aux.c:6:1: warning: unused function 'kh_destroy_r2l'
      [-Wunused-function]
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:207:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_destroy_##name(kh_##name##_t *h...
                   ^
<scratch space>:114:1: note: expanded from here
kh_destroy_r2l
^
samlib/bam_aux.c:6:1: warning: unused function 'kh_clear_r2l'
      [-Wunused-function]
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:215:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:117:1: note: expanded from here
kh_clear_r2l
^
samlib/bam_aux.c:6:1: warning: unused function 'kh_get_r2l' [-Wunused-function]
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:222:16: note: expanded from macro '__KHASH_IMPL'
        SCOPE khint_t kh_get_##name(const kh_##name##_t *h, khkey_t key...
                      ^
<scratch space>:120:1: note: expanded from here
kh_get_r2l
^
samlib/bam_aux.c:6:1: warning: unused function 'kh_put_r2l' [-Wunused-function]
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:299:16: note: expanded from macro '__KHASH_IMPL'
        SCOPE khint_t kh_put_##name(kh_##name##_t *h, khkey_t key, int *ret) \
                      ^
<scratch space>:126:1: note: expanded from here
kh_put_r2l
^
samlib/bam_aux.c:6:1: warning: unused function 'kh_del_r2l' [-Wunused-function]
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:341:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:131:1: note: expanded from here
kh_del_r2l
^
8 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. samlib/bam.c -o bam.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. samlib/bam_import.c -o bam_import.o
samlib/bam_import.c:18:1: warning: unused function 'kh_clear_ref'
      [-Wunused-function]
KHASH_MAP_INIT_STR(ref, uint64_t)
^
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:215:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:99:1: note: expanded from here
kh_clear_ref
^
samlib/bam_import.c:18:1: warning: unused function 'kh_get_ref'
      [-Wunused-function]
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:222:16: note: expanded from macro '__KHASH_IMPL'
        SCOPE khint_t kh_get_##name(const kh_##name##_t *h, khkey_t key...
                      ^
<scratch space>:102:1: note: expanded from here
kh_get_ref
^
samlib/bam_import.c:18:1: warning: unused function 'kh_del_ref'
      [-Wunused-function]
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:341:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:113:1: note: expanded from here
kh_del_ref
^
3 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. samlib/bam_index.c -o bam_index.o
samlib/bam_index.c:64:1: warning: unused function 'kh_clear_i'
      [-Wunused-function]
KHASH_MAP_INIT_INT(i, bam_binlist_t)
^
./khash.h:586:2: note: expanded from macro 'KHASH_MAP_INIT_INT'
        KHASH_INIT(name, khint32_t, khval_t, 1, kh_int_hash_func, kh_int...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:215:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:103:1: note: expanded from here
kh_clear_i
^
samlib/bam_index.c:64:1: warning: unused function 'kh_del_i' [-Wunused-function]
./khash.h:586:2: note: expanded from macro 'KHASH_MAP_INIT_INT'
        KHASH_INIT(name, khint32_t, khval_t, 1, kh_int_hash_func, kh_int...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:341:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:117:1: note: expanded from here
kh_del_i
^
2 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. samlib/sam_header.c -o sam_header.o
samlib/sam_header.c:9:1: warning: unused function 'kh_clear_str'
      [-Wunused-function]
KHASH_MAP_INIT_STR(str, const char *)
^
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:215:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_clear_##name(kh_##name##_t *h...
                   ^
<scratch space>:569:1: note: expanded from here
kh_clear_str
^
samlib/sam_header.c:9:1: warning: unused function 'kh_del_str'
      [-Wunused-function]
./khash.h:617:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:358:2: note: expanded from macro 'KHASH_INIT'
        KHASH_INIT2(name, static kh_inline, khkey_t, khval_t, kh_is_map...
        ^
./khash.h:355:2: note: expanded from macro 'KHASH_INIT2'
        __KHASH_IMPL(name, SCOPE, khkey_t, khval_t, kh_is_map, __hash_fu...
        ^
./khash.h:341:13: note: expanded from macro '__KHASH_IMPL'
        SCOPE void kh_del_##name(kh_##name##_t *h, khint_t x...
                   ^
<scratch space>:583:1: note: expanded from here
kh_del_str
^
2 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. bedutil.c -o bedutil.o	
bedutil.c:178:13: warning: unused function 'reg_destroy' [-Wunused-function]
static void reg_destroy(bedreglist_t *reg, bedvoid_destroy func) 
            ^
bedutil.c:584:13: warning: unused function 'bed_view' [-Wunused-function]
static void bed_view(regHash_t *reghash, char *reg)
            ^
2 warnings generated.
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. commons.c -o commons.o	
commons.c:3:13: warning: unused function 'stderr_print' [-Wunused-function]
static void stderr_print(char *format, ...)
            ^
1 warning generated.
.../envs/wes/bin/x86_64-apple-darwin13.4.0-ar -csru libbam.a bgzf.o kstring.o bam_aux.o bam.o bam_import.o bam_index.o sam_header.o bedutil.o commons.o
.../envs/wes/bin/x86_64-apple-darwin13.4.0-ranlib: object: libbam.a(bgzf.o) malformed object (unknown load command 1)
.../envs/wes/bin/x86_64-apple-darwin13.4.0-ar: internal ranlib command failed
make: *** [Makefile:23: libbam.a] Error 1

I don't know how to fix this problem, I hope you can provide some suggestions. Thanks！

**Comment by shiquan** [comment]
It looks like you didn't use the `ar` and `ranlib` properly. You use Apple's `ar` and `ranlib` to link objects, however these objects generated by`gcc` (I am not sure how you install it). So my suggestion is you should install `ar` and `ranlib` in the same way as you install `gcc`.

**Comment by shiquan** [comment]
If you fix this problem, I will close this issue?

**Comment by Garvin-Hu** [comment]
> If you fix this problem, I will close this issue?

Sorry, I've been busy recently and haven't solved it yet, still working on it!

**Comment by shiquan** [comment]
closed

**Comment by Garvin-Hu** [comment]
Hi, shiquan. Thank you for your tips, the issue has been solved!
