### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by evenif2000** [shiquan/bamdst#24]
hi，When I installed bamdst，I get this error:
$ make

rm -fr gmon.out *.o a.out *.exe *.dSYM  bamdst *~ *.a target.dep *.plot *.report *.tsv.gz uncover.bed
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. bgzf.c -o bgzf.o
bgzf.c: In function ‘bgzf_close’:
bgzf.c:435:18: warning: variable ‘count’ set but not used [-Wunused-but-set-variable]
  435 |         int ret, count, block_length;
      |                  ^~~~~
bgzf.c: In function ‘bgzf_check_EOF’:
bgzf.c:59:34: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   59 | #define _bgzf_read(fp, buf, len) fread(buf, 1, len, fp)
      |                                  ^~~~~~~~~~~~~~~~~~~~~~
bgzf.c:467:9: note: in expansion of macro ‘_bgzf_read’
  467 |         _bgzf_read(fp->fp, buf, 28);
      |         ^~~~~~~~~~
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. kstring.c -o kstring.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. samlib/bam_aux.c -o bam_aux.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. samlib/bam.c -o bam.o
In file included from /usr/include/string.h:495,
                 from samlib/bam.h:47,
                 from samlib/bam.c:5:
In function ‘strncpy’,
    inlined from ‘bam_header_write’ at samlib/bam.c:128:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ output truncated before terminating nul copying 4 bytes from a string of the same length [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. samlib/bam_import.c -o bam_import.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. samlib/bam_index.c -o bam_index.o
samlib/bam_index.c: In function ‘bam_index_core’:
samlib/bam_index.c:178:42: warning: overflow in conversion from ‘uint32_t’ {aka ‘unsigned int’} to ‘int32_t’ {aka ‘int’} changes value from ‘last_bin = 4294967295’ to ‘-1’ [-Woverflow]
  178 |         save_bin = save_tid = last_tid = last_bin = 0xffffffffu;
      |                                          ^~~~~~~~
samlib/bam_index.c: In function ‘bam_index_load_core’:
samlib/bam_index.c:335:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  335 |         fread(magic, 1, 4, fp);
      |         ^~~~~~~~~~~~~~~~~~~~~~
samlib/bam_index.c:342:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  342 |         fread(&idx->n, 4, 1, fp);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
samlib/bam_index.c:355:17: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  355 |                 fread(&size, 4, 1, fp);
      |                 ^~~~~~~~~~~~~~~~~~~~~~
samlib/bam_index.c:358:25: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  358 |                         fread(&key, 4, 1, fp);
      |                         ^~~~~~~~~~~~~~~~~~~~~
samlib/bam_index.c:362:25: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  362 |                         fread(&p->n, 4, 1, fp);
      |                         ^~~~~~~~~~~~~~~~~~~~~~
samlib/bam_index.c:366:25: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  366 |                         fread(p->list, 16, p->n, fp);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
samlib/bam_index.c:376:17: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  376 |                 fread(&index2->n, 4, 1, fp);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
samlib/bam_index.c:380:17: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  380 |                 fread(index2->offset, index2->n, 8, fp);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. samlib/sam_header.c -o sam_header.o
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. bedutil.c -o bedutil.o	
bedutil.c: In function ‘regcore_uniq’:
bedutil.c:256:12: warning: variable ‘lastbeg’ set but not used [-Wunused-but-set-variable]
  256 |   uint32_t lastbeg = 0;
      |            ^~~~~~~
At top level:
bedutil.c:589:13: warning: ‘bed_view’ defined but not used [-Wunused-function]
  589 | static void bed_view(regHash_t *reghash, char *reg)
      |             ^~~~~~~~
bedutil.c:180:13: warning: ‘reg_destroy’ defined but not used [-Wunused-function]
  180 | static void reg_destroy(bedreglist_t *reg, bedvoid_destroy func)
      |             ^~~~~~~~~~~
gcc -c -g -Wall -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DBGZF_CACHE -Isamlib/ -I. commons.c -o commons.o	
commons.c:3:13: warning: ‘stderr_print’ defined but not used [-Wunused-function]
    3 | static void stderr_print(char *format, ...)
      |             ^~~~~~~~~~~~
ar -csru libbam.a bgzf.o kstring.o bam_aux.o bam.o bam_import.o bam_index.o sam_header.o bedutil.o commons.o
ar: `u' modifier ignored since `D' is the default (see `U')
gcc -g -Wall -O2  -o bamdst   bamdst.c -L.  -Isamlib/ -I. -lm -lbam -lz
bamdst.c: In function ‘init_loopbams_parameters’:
bamdst.c:663:17: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  663 |     if (outdir) chdir(outdir);
      |                 ^~~~~~~~~~~~~
bamdst.c: In function ‘write_unover_file’:
bamdst.c:821:17: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  821 |     if (outdir) chdir(outdir);
      |                 ^~~~~~~~~~~~~
bamdst.c: In function ‘load_bamfiles’:
bamdst.c:837:17: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  837 |     if (outdir) chdir(outdir); // FIXME: if there is no such dir?
      |                 ^~~~~~~~~~~~~
bamdst.c: In function ‘print_report’:
bamdst.c:1064:17: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1064 |     if (outdir) chdir(outdir);
      |                 ^~~~~~~~~~~~~
At top level:
bamdst.c:78:18: warning: ‘WINDOW_SIZE’ defined but not used [-Wunused-const-variable=]
   78 | static const int WINDOW_SIZE = 102400;
      |                  ^~~~~~~~~~~

**Comment by shiquan** [comment]
It's safe to skip these warnings.
