### ISSUE TITLE
@@ ERROR ABORT @@ bam files are not properly sorted

### ISSUE THREAD

**Issue by evenif2000** [shiquan/bamdst#25]
when use as ,bamdst -p <probe.bed> -o ./ in1.bam ,the bamdst give the error: bam files are not properly sorted. Could anyone help me ?

**Comment by shiquan** [comment]
Try to use samtools or sambamba sort your bam file by genomic coordinate.

**Comment by evenif2000** [comment]
Thank u very much.Your advice solve my problem.
