### ISSUE TITLE
Suggestion - making a bioconda recipe

### ISSUE THREAD

**Issue by tamuanand** [shiquan/bamdst#26]
Hi @shiquan 

Thanks for the great tool  - I would suggest making this into a Bioconda recipe and having this installable/available via Bioconda - something similar to how csvtk is in bioconda - https://bioinf.shenwei.me/csvtk/download/#method-2-install-via-conda-latest-stable-version

Just a suggestion - it would be a great utility via bioconda

Thanks

**Comment by xdgene** [comment]
conda install xdgene::bamdst
