### ISSUE TITLE
error 404 Issue installing private repos with devtools

### ISSUE THREAD

**Issue by elviszhwx** [shiquan/bamdst#28]
If I follow the installation instructions using install_github("shiquan/bamdst") I get:
> install_github("shiquan/bamdst")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`shiquan`) and repo name (`bamdst`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

However, the installation succeeded when I tried another: install_github("tidyverse/ggplot2")
Anyone could have some advice please?

**Comment by shiquan** [comment]
Try to read the readme file plz. This is NOT a R package..
