### ISSUE TITLE
specifying more than one --cutoffdepth value

### ISSUE THREAD

**Issue by Anupriya014** [shiquan/bamdst#3]
Hi Shiquan! 
I am trying to get many coverage for a BAM file. In Bamdst tool we can do this by specifying --cutoffdepth parameter, but I need to get all these coverage in a single coverage.report. How can I get this?
I tried below command but it's giving default coverage such as 0x, 4x, 10x, 30x ,100x along with first specified --cutoffdepth value "50x".

/home//softwares/bamdst-master/bamdst -p /home/packages/SureSelect_Human_All_Exon_V5+UTRs_S04380219_Aglilent/S04380219_Covered.bed -o /home//trial/bam_stat_trial /home/trial.sorted.bam --cutoffdepth 50,40,20

Please help. 
Thank you

**Comment by BhaktiLimaye** [comment]
Hi Shiquan !
I am also interested in specifying user defined cut-offs. For targeted sequencing , 4X/10X.30X are very low cut-offs. I want to view bamfile based upon the higher cut-offs such as 200X/500X/1000X. 
How can I set this cut-off in bamdst ?
Can you please also let me know how cna I cite bamdst if I used it in my work ?
Thanks

**Comment by hupef** [comment]
Hi Shiquan !
Have this request been solved?

**Comment by BhaktiLimaye** [comment]
Hello Shiquan,
  No not yet. So I wrote my own script for calculation of the same. However if it is still possible with bamdst please let me know.
Thanks

**Comment by xiucz** [comment]
Have this request been solved?

**Comment by shiquan** [comment]
now support.
