### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Alipe2021** [shiquan/bamdst#30]
Hi shiquan:
  When the following simple script was executed, It crashed and threw `Segmentation fault (core dumped)`.

```sh
/opt/bio/bamdst/bamdst -p genome.bed -o sampleA_state sampleA.bam 
```
I used the Linux Distribution: openSUSE 15.3

![image](https://user-images.githubusercontent.com/77709930/191888676-52f928e1-0977-4e22-ab63-231f41fbac6a.png)

  Is there a bug in bamdst? How can I fix it?

  Wish your comments, Thanks!

**Comment by shiquan** [comment]
Can you head your bed file or send it to me?

**Comment by Alipe2021** [comment]
> Can you head your bed file or send it to me?

The bed file was fetched from the .fai file with the script:
```sh
cat genome.fa.fai | awk '{print $1"\t1\t"$2}' > genome.bed
```
the head 10 lines are as follows:
```txt
1       1       307041717
2       1       244442276
3       1       235667834
4       1       246994605
5       1       223902240
6       1       174033170
7       1       182381542
8       1       181122637
9       1       159769782
10      1       150982314
```

**Comment by shiquan** [comment]
This is a memory issue. The bed regions are too large to allocate memory. The bamdst original was designed for capturing regions and I didn't consider the large memory requirement. My suggestion is to try to split a chromosome region into a few non-overlapped and unconnected regions and rerun it.
