### ISSUE TITLE
Multi-genomes

### ISSUE THREAD

**Issue by TKsh6** [shiquan/bamdst#31]
How can I do to get the final report of multi-genomes? Cause I got many bins(MAGs) within several contigs after `metabat` ,and I want to know the mapping ratio of each MAG. However, the fraction of mapped reads in the ` coverage-report.txt` total ratio, so how can I do to get the ratio of each MAG through one process of blast.

**Comment by shiquan** [comment]
I didn't get it, what do you mean to get the 'alignment ratio' of each MAG?

**Comment by TKsh6** [comment]
It's the `Fraction of Mapped Reads` in the `coverage.report`, the comparison result of the reads and the reference. And my problem is that there are many genomes(species) in one reference file, with several contigs within one genome. for example, the first column in my bed file may be like this,
```
CMEBWM1_bin.100_cg1
CMEBWM1_bin.100_cg2
CMEBWM1_bin.100_cg3
CMEBWM1_bin.100_cg4
CMEBWM1_bin.100_cg5
CMEBWM1_bin.100_cg6
CMEBWM1_bin.101_cg1
CMEBWM1_bin.101_cg2
CMEBWM1_bin.101_cg3
CMEBWM1_bin.101_cg4
...
```
What I want to get is the mapping fraction of CMEBWM1_bin.100,CMEBWM1_bin.101,et...in the reads.

yours tk,

**Comment by shiquan** [comment]
But I don't think it's possible to get the unmapped reads for each bin, right?

**Comment by TKsh6** [comment]
Yes, you are right.
So, this means that I need to blast for each bin,  not at one time? Because, If I do as above, I can only get the coverage of each cogtig(`chromosome.report`) ,not each bin.

**Comment by shiquan** [comment]
Maybe you need check the region.tsv.gz. I will close this issue, let me know if you have any further question.
