### ISSUE TITLE
[Target] Coverage (>0x)    100.00%  but uncover.bed is not umpty

### ISSUE THREAD

**Issue by step1xiao** [shiquan/bamdst#33]
Hi,
i am confused about the workout, coverage.report file shows [Target] Coverage (>0x)    100.00% but uncover.bed shows 72 point. whether bam cover the full bed.
Thanks!

**Comment by shiquan** [comment]
Uncover bed file includes regions with depth low than 5 by default. Please check `--uncover` parameter.
