### ISSUE TITLE
question about long reads

### ISSUE THREAD

**Issue by crazysummerW** [shiquan/bamdst#36]
hello,
I wonder if bamdst can perform statistics on aligned BAM files containing long reads, such as BAM files from PacBio.

Looking forward to your reply.
Thanks.

**Comment by shiquan** [comment]
Bamdst check the read alignment info from sam FLAG, so I think it should work for any BAM file. You can try and feedback if any issue.

**Comment by crazysummerW** [comment]
@shiquan 
Thanks for you reply.

Do you have any good solutions to solve memory issues for WGS data? Or is bamdst available for multi-threaded analysis?

**Comment by shiquan** [comment]
bamdst is designed for WES and panel, and I didn't consider WGS and multi-threads in the first place. Therefore, I need to redesign this tool to support WGS and multi-threads, which may not be necessary, considering so much software already exists for similar jobs.
However, you can still run bamdst for WGS by dividing the whole genome region into small regions.
