### ISSUE TITLE
about the depth.tsv.gz

### ISSUE THREAD

**Issue by work-liuyang** [shiquan/bamdst#37]
hello, 
      I want to know why the depth.tsv.gz  stats depth startint with position 2 instead position 1

thanks !

**Comment by work-liuyang** [comment]
It‘s my problem, sorry,  there is nothing to do.

**Comment by wutian1217** [comment]
Hi, I also met the same problem: the depth starts from position 2 instead of 1. Could you show where the problem is? Thanks

**Comment by shiquan** [comment]
I wondering the position in your  bed file is start from 1 right? But it should start from 0.

**Comment by shiquan** [comment]
http://www.xtaohub.com/BI-solutions/bed-file-format.html
