### ISSUE TITLE
how to use MapQ to filter read at target average depth counts (rmdup) ?

### ISSUE THREAD

**Issue by zeronot** [shiquan/bamdst#4]
HI, 
   I got a question . 
   If I set -q 10,  it means  if the read mapQ  is less than 10, then this read won't count to calculate target average detph (rmdup) ??
  am  I  right ?
  thank you !

**Comment by zeronot** [comment]
@shiquan thank you !

**Comment by shiquan** [comment]
Hi, thank you for your question about the mapQ and read counts. The map quality and duplicated reads are two different conditions to filter reads. If set -q 10, all the reads with mapQ higher than 10 will be count and export in coverage report as "[Total] Fraction of MapQ reads in xxx", however, bamdst will NOT filter low quality (mapQ <=10) when counting the average depth or rmduped average depth.

**Comment by shiquan** [comment]
Hi, thank you for your question about map quality and rmdup depth. You are right, duplicated reads and low mapQ reads (< -q INT) will be skipped when trying to calculate rmdup depth.

**Comment by tfmorris** [comment]
Note that there's currently a bug (#12) in this area which means that low map quality reads are not being filtered in the rmdup count. The PR #13 fixes this.
