### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tfmorris** [shiquan/bamdst#5]
This looks like a cool tool, but I'm unsure what license it's made available under. Some of the C files contain headers with Broad or BGI copyrights and MIT licenses, but others have no headers.

Could you make the license explicit by creating a LICENSE file or some other license statement (after reviewing all the included code to make sure it's compatible, of course).

Thanks!

**Comment by shiquan** [comment]
Thank you for your kindly reminder. A license file just created.

**Comment by tfmorris** [comment]
Thanks, but I don't see any commits to the repo since July. Do your changes need to be pushed to the public repo?

**Comment by shiquan** [comment]
Yes. It's my mistake, and I just found it...
