### ISSUE TITLE
Memory Bugs

### ISSUE THREAD

**Issue by yzhang88** [shiquan/bamdst#8]
I met a problem like this:
@@ ERROR ABORT @@
[NeedMEM] trying to allocate 565656160 bytes (limits: 500000000)

And how to deal with it?

**Comment by shiquan** [comment]
I think you may try to calculate the depth and coverage for a vast region right? I am trying to redesign this program to fix such problems but not so soon. Maybe you can split this region into several unconnected pieces for now.

**Comment by yzhang88** [comment]
Ah, I forgot to mention. I used it to calculate WGS data....

**Comment by shiquan** [comment]
That makes senses. This software only designed for captured data. My suggestion is to split each chromosome into several regions (such as cytoBand). Meanwhile, please follow this issue, I will close it until the new release published.

**Comment by ArsFc** [comment]
the bed start pos not set to zero
